version: '3.8'
services:
  client: 
    build: ./client
    ports:
      - "3000:3000"
    container_name: chatbot-client-docker
    restart: always
    links: 
      - server
  server:
    build: ./server
    ports: 
    - "8000:8000"
    container_name: chatbot-server-docker
    restart: always